### ISSUE TITLE
cargo checkmate needs to be integrated

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#11]
Click:

Security -->  Code security and analysis --> Code scanning ("Set up") --> Configure other scanning tools --> "set up a workflow yourself"

This provides a `yml` you can use as a start point to set up `checkmate` to scan the repo.

Perhaps you can click through the above cheese-maze in `zecwalletlitelib` to get a different template (more Rust flavored).

Hookup `checkmate` to run in some reasonable way.

Lather-Rinse-Repeat on all Rust containing repos in zingolabs.

**Comment by zancas** [comment]
Here's a sample of the auto-generated `.github/workflows/main.yml`:

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
```
